name: Deploy Static Web App to Azure

on:
  push:
    branches:
      - main  # alebo iná vetva, ak používaš inú

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to Azure
        uses: Azure/static-web-apps-deploy@v1
        with:
          app_location: "/" # cesta k tvojmu frontend projektu
          output_location: "/dist" # výstupový priečinok po build (napríklad pre React "build")
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
