name: Deploy Static Web App to Azure

on:
  push:
    branches:
      - main  # Alebo tvoja hlavná vetva

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload static files to Azure
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} 
          action: "upload"
          app_location: "/"  # Koreňový priečinok
          output_location: "/"  # Statické súbory sú priamo v koreňovom priečinku
